/**
 * Monorepo-wide ESLint configuration.
 *
 * `@sorrell/eslint-config` still ships a legacy (eslintrc-shaped) config
 * object — `extends`/`parser`/`plugins`(as string names)/`ignorePatterns` —
 * not a flat config. Passed directly to `defineConfig()`, none of those
 * keys mean anything to ESLint 9's flat config engine, so the whole thing
 * silently contributes zero rules and zero file matching (every file comes
 * back "ignored because no matching configuration was supplied", which is
 * why the VS Code ESLint extension found nothing to report). `FlatCompat`
 * is ESLint's own bridge for exactly this: it resolves the `extends`/
 * `parser`/`plugins` strings against real packages and produces proper
 * flat-config objects.
 *
 * @file      eslint.config.js
 * @author    Gage Sorrell <gage@sorrell.sh>
 * @copyright (c) 2026 Gage Sorrell
 * @license   MIT
 */

import Js from "@eslint/js";
import { FlatCompat } from "@eslint/eslintrc";
import SorrellConfig from "@sorrell/eslint-config";
import { defineConfig } from "eslint/config";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const CompatBaseDirectory = path.dirname(fileURLToPath(import.meta.url));

const Compat = new FlatCompat({
    baseDirectory: CompatBaseDirectory,
    resolvePluginsRelativeTo: CompatBaseDirectory,
    /* `SorrellConfig.extends` includes "eslint:recommended"; FlatCompat needs
       its flat-config equivalent supplied explicitly to resolve that. */
    recommendedConfig: Js.configs.recommended
});

export default defineConfig(
    Compat.config(SorrellConfig),
    {
        /* ESLint ignores dot-directories by default (`.rnstorybook`,
           `.expo`, ...). `.rnstorybook/stories/*` and its `main.ts`/
           `preview.tsx` are hand-written source, not generated output, so
           un-ignore them; `storybook.requires.ts` (auto-generated by
           Storybook itself — "do not edit") stays ignored. */
        ignores: [ "!**/.rnstorybook/**" ]
    },
    {
        ignores: [ "**/.rnstorybook/storybook.requires.ts" ]
    },
    {
        /* Storybook story files are demo/config code, not documented API
           surface, so don't require JSDoc blocks on their exports. */
        files: [ "Application/**/*.stories.tsx" ],
        rules:
        {
            "jsdoc/require-jsdoc": "off"
        }
    },
    {
        rules:
        {
            "jsdoc/no-blank-block-descriptions": "off",
            "jsdoc/sort-tags":
            [
                "error",
                {
                    reportIntraTagGroupSpacing: false,
                    reportTagGroupSpacing: false,
                    tagSequence:
                    [
                        {
                            tags:
                            [
                                "module",
                                "internal",
                                "file",
                                "author",
                                "copyright",
                                "license"
                            ]
                        }
                    ]
                }
            ]
        }
    }
);
