/**
 * Monorepo-wide ESLint configuration.
 *
 * `@sorrell/eslint-config` is a flat config (ESLint 9): it already carries
 * its `plugins` (as objects), `files` globs, `extends`, and rules, so it is
 * spread straight into `defineConfig`.  It must *not* be passed through
 * `FlatCompat` — that bridge is only for legacy, eslintrc-shaped configs, and
 * handing it flat plugin objects (whose `@typescript-eslint` entry is a
 * circular graph) crashes ESLint while it tries to JSON-serialize them for
 * schema validation ("Converting circular structure to JSON").
 *
 * @file      eslint.config.js
 * @author    Gage Sorrell <gage@sorrell.sh>
 * @copyright (c) 2026 Gage Sorrell
 * @license   MIT
 */

import SorrellConfig from "@sorrell/eslint-config";
import { defineConfig } from "eslint/config";

export default defineConfig(
    SorrellConfig,
    {
        /* ESLint ignores dot-directories by default (`.rnstorybook`,
           `.expo`, ...). `.rnstorybook/stories/*` and its `main.ts`/
           `preview.tsx` are hand-written source, not generated output, so
           un-ignore them; `storybook.requires.ts` (auto-generated by
           Storybook itself — "do not edit") stays ignored. */
        ignores: [ "!**/.rnstorybook/**" ]
    },
    {
        ignores: [ "**/.rnstorybook/storybook.requires.ts" ]
    },
    {
        /* Storybook story files are demo/config code, not documented API
           surface, so don't require JSDoc blocks on their exports. */
        files: [ "Application/Mobile/**/*.stories.tsx" ],
        rules:
        {
            "jsdoc/require-jsdoc": "off"
        }
    },
    {
        rules:
        {
            "@sorrell/jsdoc-file-name": "error",
            "@typescript-eslint/no-require-imports": "off",
            "jsdoc/no-blank-block-descriptions": "off",
            "jsdoc/sort-tags":
            [
                "error",
                {
                    reportIntraTagGroupSpacing: false,
                    reportTagGroupSpacing: false,
                    tagSequence:
                    [
                        {
                            tags:
                            [
                                "module",
                                "internal",
                                "file",
                                "author",
                                "copyright",
                                "license"
                            ]
                        }
                    ]
                }
            ]
        }
    }
);
